### ISSUE TITLE
hyperdrive 6.0 exception

### ISSUE THREAD

**Issue by Arkotek** [mafintosh/hyperdrive#52] opened 2016-06-03 14:21 UTC
Since the latest hyperdrive update (6.0) I get this exception:

```
Uncaught TypeError: peer.emit is not a function
    at Channel.onend (node_modules/hyperdrive/node_modules/hypercore/lib/replicate.js:203:8)
    at Protocol._close (node_modules/hyperdrive/node_modules/hypercore/node_modules/hypercore-protocol/index.js:492:13)
    at Protocol.onfinalize (node_modules/hyperdrive/node_modules/hypercore/node_modules/hypercore-protocol/index.js:193:14)
    at Protocol.Duplexify._destroy (node_modules/hyperdrive/node_modules/hypercore/node_modules/hypercore-protocol/node_modules/duplexify/index.js:191:8)
    at node_modules/hyperdrive/node_modules/hypercore/node_modules/hypercore-protocol/node_modules/duplexify/index.js:174:10
```

Hyperdrive version: 6.0
Hypercore version: 4.1.0
Hypercore protocol: 4.3.0

Regards,

**Comment by mafintosh** [comment] 2016-06-03 14:55
Do you have a reproducible test case by any chance?

**Comment by mafintosh** [comment] 2016-06-03 15:50
was caused by a bug in hypercore 4.1.0 - if you reinstall it should be fixed. sorry about that.

**Closed** 2016-06-03 15:49 UTC
